name: drGAT
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.10.
  - pip:
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pandas==2.2.2
      - torch==2.0.1
      - torch-geometric==2.3.1
